version: '3.9'

services:
  web:
    build:
      context: .
    container_name: blog_web
    command: ["/app/entrypoint.sh"]
    ports:
      - "7001:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media

  db:
    image: postgres:14
    container_name: blog_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: blog_redis
    volumes:
      - redis_data:/data

  celery_worker:
    build:
      context: .
    container_name: blog_celery_worker
    command: celery -A shop_api worker --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - .env
    volumes:
      - .:/app

  celery_beat:
    build:
      context: .
    container_name: blog_celery_beat
    command: celery -A shop_api beat --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - .env
    volumes:
      - .:/app

  celery_flower:
    build:
      context: .
    container_name: blog_celery_flower
    command: celery -A shop_api flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    container_name: blog_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  db_data:
  redis_data:
  static_volume:
  media_volume:
